name: 'Right Auto Get Points'

on:
  push:
    branches: 
      - master
#  schedule:
#    - cron: '0 17 * * *'

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: python -m pip install --upgrade requests
    - name: 'Get points'
      env:
        RIGHT_USERNAME: ${{ secrets.RIGHT_USERNAME }}
        RIGHT_PASSWORD: ${{ secrets.RIGHT_PASSWORD }}
      run: python right_get_points.py
